#the return keyword
def volume_calculator(height,lenght,breadth):
    volume = int(height) * int(lenght) * int(breadth)
    print(f'The volume of your shape is {volume}')  

#volume_calculator(20,10,3)

def volume_calculatorss(height,lenght,breadth):
    volume = int(height) * int(lenght) * int(breadth)
    return f'The volume of your shape is {volume}'

print(volume_calculatorss(10,20,30))

def volumess_calculatorss(height,lenght,breadth):
    volume = int(height) * int(lenght) * int(breadth)
    return volume
    print("hahah")

#print(f'Total volume for 3  cylinders is {volumess_calculatorss(10,20,30) + volumess_calculatorss(30,20,45) + volumess_calculatorss(10,20,15)}')
#print(type(volumess_calculatorss(10,20,30)))



#LOOP

#for loop
#while loop

#\/\/\/\/

#type print("Hello World")
# Dear Learner, our first example using a function is to print  Hello worlds, type print("Hello World")

#print("Dear Learner, our first example using a function is to print  Hello worlds, type print(\"\Hello World\")")
# Emma missed classes.
# Simoen bought Tissue.
# Emmag is a hundrednaire.

#print('I\'m a boy')
#print("Emma missed classes. \nSimoen bought Tissue. \nEmmag is a hundrednaire.")

#print("type print("Hello World")")
#for number in range(1,100):
#    print(number)

#      \n       \\   \t     
#print("Emma missed classes. \nSimoen bought Tissue. \nEmmag is a hundrednaire.")
#print()


